/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AlertSeverity = "CRITICAL" | "HIGH" | "INFO" | "WARNING";

export type AlertStatus = "ACKNOWLEDGED" | "CLOSED" | "IN_PROGRESS" | "OPEN" | "RESOLVED";

export type BottleStatus = "DAMAGED" | "EMPTY" | "EXPIRED" | "IN_STOCK" | "INSTALLED" | "LIQUIDATED" | "LOW";

export type BrandStatus = "ACTIVE" | "DISABLED" | "SUSPENDED";

export type CommandStatus = "ACKNOWLEDGED" | "CREATED" | "EXPIRED" | "FAILED" | "REJECTED" | "SENT" | "SUCCEEDED" | "UNKNOWN";

export type CredentialStatus = "ACTIVE" | "EXPIRED" | "REVOKED";

export type DispenseType = "CUSTOMER" | "DIAGNOSTIC";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type KioskInteractionType = "PRODUCT_IMPRESSION" | "PRODUCT_SELECTED";

export type MachineConnectionStatus = "OFFLINE" | "ONLINE" | "UNSTABLE";

export type MachineOperatingMode = "DISABLED" | "MAINTENANCE" | "NORMAL";

export type NotificationStatus = "FAILED" | "PENDING" | "READ" | "SENT";

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrderStatus = "CREATED" | "DISPENSE_REQUESTED" | "DISPENSED" | "EXPIRED" | "FAILED" | "PAID" | "PENDING_PAYMENT" | "REFUND_PENDING" | "REFUNDED";

export type PaymentStatus = "CANCELLED" | "EXPIRED" | "FAILED" | "PARTIALLY_REFUNDED" | "PENDING" | "REFUND_PENDING" | "REFUNDED" | "SUCCEEDED";

export type RefillRequestReason = "EXPIRING" | "LOW_STOCK" | "PRODUCT_CHANGE";

export type RefillRequestStatus = "ACCEPTED" | "CANCELLED" | "COMPLETED" | "REJECTED" | "SCHEDULED" | "SUBMITTED";

export type RefillStatus = "CANCELLED" | "COMPLETED" | "STARTED";

export type RevenueOwnerType = "BRAND" | "PLATFORM";

export type ShipmentDeclarationStatus = "CANCELLED" | "DECLARED" | "DISCREPANCY" | "RECEIVED";

export type SlotRentalRequestStatus = "APPROVED" | "CANCELLED" | "CONVERTED" | "REJECTED" | "REQUESTED";

export type SlotRentalStatus = "ACTIVE" | "CLOSED" | "DRAFT" | "EXPIRING" | "GRACE" | "LIQUIDATED" | "RENEWED" | "TERMINATED";

export type SlotStatus = "AVAILABLE" | "DISABLED" | "MAINTENANCE" | "UNAVAILABLE";

export type TicketPriority = "CRITICAL" | "HIGH" | "LOW" | "MEDIUM";

export type TicketStatus = "ASSIGNED" | "CLOSED" | "IN_PROGRESS" | "OPEN" | "POST_TEST" | "REOPENED" | "RESOLVED" | "WAITING_PART";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserStatus = "ACTIVE" | "DISABLED" | "INVITED" | "LOCKED";

export interface Alerts {
  acknowledged_at: Timestamp | null;
  acknowledged_by: string | null;
  assigned_to: string | null;
  /**
   * CHỈ có giá trị với cảnh báo mức slot, khi biết chắc một thương hiệu (vd FR-ALR-02). NULL với cảnh báo mức máy (FR-ALR-01/03/05) vì có thể ảnh hưởng nhiều thương hiệu cùng lúc — FR-ALR-09 suy ra danh sách thương hiệu bị ảnh hưởng lúc đọc, bằng cách join slot_rentals đang hiệu lực của máy, KHÔNG lấy từ cột này.
   */
  brand_id: string | null;
  created_at: Generated<Timestamp>;
  deduplication_key: string;
  description: string | null;
  first_occurred_at: Timestamp;
  id: Generated<string>;
  last_occurred_at: Timestamp;
  machine_id: string;
  occurrence_count: Generated<number>;
  resolution: string | null;
  resolved_at: Timestamp | null;
  resolved_by: string | null;
  severity: AlertSeverity;
  slot_id: string | null;
  status: Generated<AlertStatus>;
  title: string;
  type: string;
}

export interface AuditLogs {
  action: string;
  actor_id: string | null;
  actor_type: string;
  after_data: Json | null;
  before_data: Json | null;
  /**
   * NULL với sự kiện mức nền tảng.
   */
  brand_id: string | null;
  id: Generated<string>;
  metadata: Json | null;
  occurred_at: Generated<Timestamp>;
  severity: Generated<string>;
  source_ip: string | null;
  target_id: string | null;
  target_type: string;
  user_agent: string | null;
}

export interface Bottles {
  batch_id: string;
  /**
   * Thương hiệu gốc, bất biến để phục vụ kiểm toán kể cả sau khi quyền sở hữu chuyển về nền tảng.
   */
  brand_id: string;
  created_at: Generated<Timestamp>;
  current_estimated_ml: Numeric;
  current_measured_weight_g: Numeric | null;
  empty_weight_g: Numeric | null;
  expires_at: Timestamp | null;
  fragrance_product_id: string;
  id: Generated<string>;
  identifier: string;
  initial_measured_weight_g: Numeric | null;
  initial_volume_ml: Numeric;
  installed_at: Timestamp | null;
  liquidated_at: Timestamp | null;
  opened_at: Timestamp | null;
  /**
   * Chủ sở hữu hiện tại. Lật sang PLATFORM khi thanh lý (FR-EXP-15). Đây mới là cột quyết định quyền sở hữu, không phải brand_id.
   */
  owner: Generated<RevenueOwnerType>;
  removed_at: Timestamp | null;
  /**
   * Hợp đồng mà chai đang phục vụ tại thời điểm thanh lý (FR-EXP-16).
   */
  source_rental_id: string | null;
  status: Generated<BottleStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Brands {
  code: string;
  contact_info: Json | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  kiosk_content: Json | null;
  logo_url: string | null;
  name: string;
  status: Generated<BrandStatus>;
  updated_at: Generated<Timestamp>;
}

export interface BrandShipmentDeclarations {
  brand_id: string;
  created_at: Generated<Timestamp>;
  declared_bottle_volume_ml: Numeric;
  declared_by: string;
  declared_quantity: number;
  /**
   * Bắt buộc khi received_quantity khác declared_quantity (FR-INV-25).
   */
  discrepancy_notes: string | null;
  expected_ship_date: Timestamp | null;
  fragrance_product_id: string;
  id: Generated<string>;
  received_at: Timestamp | null;
  received_by: string | null;
  received_quantity: number | null;
  status: Generated<ShipmentDeclarationStatus>;
  updated_at: Generated<Timestamp>;
}

export interface DeviceCredentials {
  certificate_fingerprint: string | null;
  credential_identifier: string;
  expires_at: Timestamp | null;
  id: Generated<string>;
  issued_at: Timestamp;
  last_authenticated_at: Timestamp | null;
  machine_id: string;
  public_key_or_secret_hash: string;
  revoked_at: Timestamp | null;
  status: Generated<CredentialStatus>;
}

export interface DeviceEvents {
  device_event_id: string;
  event_type: string;
  id: Generated<string>;
  machine_id: string;
  occurred_at: Timestamp;
  payload: Json | null;
  received_at: Generated<Timestamp>;
}

export interface DispenseCommands {
  acknowledged_at: Timestamp | null;
  /**
   * Có giá trị với lệnh CUSTOMER (chép từ đơn). NULL với lệnh DIAGNOSTIC chạy trên slot chưa có hợp đồng nào.
   */
  brand_id: string | null;
  /**
   * Mã lệnh duy nhất toàn hệ thống (FR-DSP-02). Thiết bị lưu lại để từ chối lệnh trùng (FR-DSP-10, lỗi CMD_DUPLICATE).
   */
  command_token: string;
  command_type: DispenseType;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  /**
   * created_at + DISPENSE_CMD_TTL_SEC (FR-DSP-06).
   */
  expires_at: Timestamp;
  id: Generated<string>;
  machine_id: string;
  order_id: string | null;
  retry_count: Generated<number>;
  sent_at: Timestamp | null;
  signature: string;
  slot_id: string;
  status: Generated<CommandStatus>;
}

export interface DispenseResults {
  brand_id: string | null;
  command_id: string;
  device_event_id: string | null;
  executed_at: Timestamp | null;
  /**
   * Chỉ dùng mã trong spec/errors.md §"Lệnh xịt": CMD_INVALID_SIGNATURE, CMD_EXPIRED, CMD_WRONG_MACHINE, CMD_DUPLICATE, DOOR_OPEN, SLOT_EMPTY, ACTUATOR_FAULT, HARD_TIMEOUT, NO_CURRENT.
   */
  failure_code: string | null;
  id: Generated<string>;
  measured_quantity_ml: Numeric | null;
  raw_payload: Json | null;
  received_at: Generated<Timestamp>;
  result_code: string | null;
  sensor_snapshot: Json | null;
  success: boolean;
}

export interface FragranceProducts {
  brand_id: string;
  created_at: Generated<Timestamp>;
  currency: Generated<string>;
  /**
   * Giá gợi ý mỗi lượt xịt, dùng làm gợi ý khi Brand Admin đặt giá slot (FR-PRD-04). Giá thực tế nằm ở slot_rentals.price_per_spray.
   */
  default_price: Numeric;
  deleted_at: Timestamp | null;
  description: string | null;
  fragrance_notes: Json | null;
  /**
   * Giá bán lẻ một chai đầy, dùng tính phí lưu kho thời gian ân hạn (FR-PRD-05, FR-EXP-10).
   */
  full_bottle_retail_price: Numeric | null;
  full_bottle_volume_ml: Numeric | null;
  id: Generated<string>;
  image_url: string | null;
  name: string;
  product_url: string | null;
  sku: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface InventoryAdjustments {
  adjusted_by: string;
  after_quantity_ml: Numeric;
  before_quantity_ml: Numeric;
  bottle_id: string;
  brand_id: string;
  created_at: Generated<Timestamp>;
  difference_ml: Numeric;
  id: Generated<string>;
  /**
   * NOT NULL: lý do là bắt buộc (FR-INV-16, lỗi ADJUSTMENT_REASON_REQUIRED).
   */
  reason: string;
  slot_id: string | null;
}

export interface InventoryBatches {
  batch_number: string;
  brand_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  expires_at: Timestamp | null;
  fragrance_product_id: string;
  id: Generated<string>;
  quantity_received: number;
  received_at: Timestamp;
  /**
   * Đặt khi lô được tạo tự động từ khai báo gửi hàng đã nhận (FR-INV-26); NULL với lô nhập thủ công.
   */
  source_declaration_id: string | null;
  supplier_info: Json | null;
}

export interface KioskInteractionEvents {
  brand_id: string;
  event_id: string;
  event_type: KioskInteractionType;
  fragrance_product_id: string;
  id: Generated<string>;
  /**
   * Phiên ẩn danh, xoay vòng — KHÔNG chứa bất kỳ định danh khách hàng nào.
   */
  kiosk_session_id: string;
  machine_id: string;
  occurred_at: Timestamp;
  received_at: Generated<Timestamp>;
  slot_id: string;
  slot_rental_id: string;
}

export interface Locations {
  address: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  status: Generated<string>;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Machines {
  configuration_version: Generated<number>;
  created_at: Generated<Timestamp>;
  display_name: string;
  firmware_version: string | null;
  id: Generated<string>;
  last_seen_at: Timestamp | null;
  location_id: string;
  /**
   * Trục chế độ, do người vận hành đặt (FR-MCH-09, FR-MNT-05/12). Độc lập với status.
   */
  operating_mode: Generated<MachineOperatingMode>;
  serial_number: string;
  simulator_enabled: Generated<boolean>;
  /**
   * Trục kết nối, suy ra từ heartbeat (FR-MCH-08, FR-IOT-01..03). Độc lập với operating_mode.
   */
  status: Generated<MachineConnectionStatus>;
  updated_at: Generated<Timestamp>;
}

export interface MachineSlots {
  /**
   * Chai đang lắp ở slot. Một slot tối đa một chai do chính cardinality của cột; chiều ngược lại (một chai không lắp ở hai slot) do uq_slot_active_bottle chặn (FR-MCH-07, ADR-0002).
   */
  active_bottle_id: string | null;
  calibrated_dosage_ml: Numeric | null;
  created_at: Generated<Timestamp>;
  estimated_remaining_ml: Generated<Numeric>;
  estimated_remaining_sprays: Generated<number>;
  id: Generated<string>;
  low_stock_threshold_ml: Numeric | null;
  machine_id: string;
  slot_number: number;
  status: Generated<SlotStatus>;
  updated_at: Generated<Timestamp>;
  /**
   * Optimistic locking cho thao tác đồng thời trên slot.
   */
  version: Generated<number>;
}

export interface MachineStatusHistories {
  changed_by: string | null;
  from_connection_status: MachineConnectionStatus | null;
  from_operating_mode: MachineOperatingMode | null;
  id: Generated<string>;
  machine_id: string;
  occurred_at: Generated<Timestamp>;
  reason: string | null;
  source: string;
  to_connection_status: MachineConnectionStatus | null;
  to_operating_mode: MachineOperatingMode | null;
}

export interface MaintenanceActivities {
  activity_type: string;
  actor_id: string;
  attachments: Json | null;
  created_at: Generated<Timestamp>;
  from_status: TicketStatus | null;
  id: Generated<string>;
  notes: string | null;
  ticket_id: string;
  to_status: TicketStatus | null;
}

export interface MaintenanceTickets {
  assigned_to: string | null;
  /**
   * Hầu như luôn NULL: phiếu bảo trì là tài nguyên của nền tảng/máy, không thuộc thương hiệu nào. FR-MNT-07 thông báo cho mọi Brand Admin có slot trên máy, suy ra bằng join slot_rentals đang hiệu lực — không lưu ở đây.
   */
  brand_id: string | null;
  category: string;
  closed_at: Timestamp | null;
  corrective_action: string | null;
  cost: Numeric | null;
  created_at: Generated<Timestamp>;
  diagnosis: string | null;
  downtime_minutes: number | null;
  due_at: Timestamp | null;
  id: Generated<string>;
  machine_id: string;
  post_test_result: string | null;
  post_tested_at: Timestamp | null;
  post_tested_by: string | null;
  priority: TicketPriority;
  replacement_parts: Json | null;
  resolved_at: Timestamp | null;
  severity: AlertSeverity;
  source_alert_id: string | null;
  started_at: Timestamp | null;
  status: Generated<TicketStatus>;
  ticket_number: string;
  updated_at: Generated<Timestamp>;
}

export interface Notifications {
  brand_id: string;
  channel: string;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  read_at: Timestamp | null;
  recipient_user_id: string;
  sent_at: Timestamp | null;
  status: Generated<NotificationStatus>;
  subject: string | null;
  type: string;
}

export interface Orders {
  /**
   * Giá đã chụp tại thời điểm tạo đơn; đổi giá slot sau đó không ảnh hưởng đơn này (FR-ORD-06, FR-SLT-09). Không có đường cập nhật (NFR-DAT-06).
   */
  amount: Numeric;
  /**
   * Thương hiệu sở hữu sản phẩm trong danh mục tại thời điểm tạo đơn — LUÔN có giá trị, kể cả với đơn phát sinh sau thanh lý (khi đó revenue_owner = PLATFORM). Quyền sở hữu tiền nằm ở revenue_owner, KHÔNG phải cột này. Màn hình của Brand Admin (FR-EXP-20, FR-REV-06) phải lọc theo revenue_owner = BRAND, không bao giờ chỉ theo brand_id.
   */
  brand_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  dispensed_at: Timestamp | null;
  /**
   * created_at + ORDER_PAYMENT_TTL_SEC (FR-ORD-09).
   */
  expires_at: Timestamp;
  failure_code: string | null;
  fragrance_product_id: string;
  id: Generated<string>;
  idempotency_key: string;
  machine_id: string;
  manual_review_resolved_at: Timestamp | null;
  manual_review_resolved_by: string | null;
  /**
   * Đặt true khi đã thanh toán nhưng lượt xịt thất bại hoặc không xác định (FR-ORD-19). Dẫn vào luồng hoàn tiền và hỗ trợ (FR-ORD-20/21).
   */
  needs_manual_review: Generated<boolean>;
  paid_at: Timestamp | null;
  payment_reference: string;
  product_name_snapshot: string;
  /**
   * Ảnh chụp bất biến tại thời điểm tạo đơn: BRAND hoặc PLATFORM (FR-REV-01/02/03). Không có đường cập nhật (NFR-DAT-06).
   */
  revenue_owner: RevenueOwnerType;
  slot_id: string;
  slot_rental_id: string;
  status: Generated<OrderStatus>;
  updated_at: Generated<Timestamp>;
}

export interface OrderStatusHistories {
  actor_id: string | null;
  actor_type: string;
  brand_id: string;
  from_status: OrderStatus | null;
  id: Generated<string>;
  metadata: Json | null;
  occurred_at: Generated<Timestamp>;
  order_id: string;
  reason: string | null;
  to_status: OrderStatus;
}

export interface PaymentEvents {
  /**
   * NULL khi webhook không khớp được với payment/order nào (chữ ký sai, mã tham chiếu lạ) — vẫn ghi lại để rà soát bảo mật (FR-ORD-13/14).
   */
  brand_id: string | null;
  id: Generated<string>;
  payload: Json;
  payload_hash: string;
  payment_id: string | null;
  processed_at: Timestamp | null;
  processing_result: string | null;
  provider: string;
  provider_event_id: string;
  received_at: Generated<Timestamp>;
  signature_valid: boolean;
}

export interface Payments {
  amount: Numeric;
  brand_id: string;
  created_at: Generated<Timestamp>;
  currency: string;
  id: Generated<string>;
  order_id: string;
  paid_at: Timestamp | null;
  provider: string;
  provider_reference: string | null;
  provider_transaction_id: string | null;
  raw_response: Json | null;
  status: Generated<PaymentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Permissions {
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
}

export interface RefillRequests {
  brand_id: string;
  created_at: Generated<Timestamp>;
  fragrance_product_id: string;
  id: Generated<string>;
  reason: RefillRequestReason;
  /**
   * Phiên nạp thực tế liên kết (FR-RFQ-08). Chỉ đặt được COMPLETED khi cột này có giá trị (FR-RFQ-09) — xem §13.
   */
  refill_session_id: string | null;
  rejection_reason: string | null;
  requested_by: string;
  reviewed_by: string | null;
  scheduled_at: Timestamp | null;
  slot_id: string;
  slot_rental_id: string;
  status: Generated<RefillRequestStatus>;
  updated_at: Generated<Timestamp>;
}

export interface RefillSessions {
  after_weight_g: Numeric | null;
  before_weight_g: Numeric | null;
  brand_id: string;
  /**
   * Cổng chặn của FR-INV-14: phải true trước khi đóng phiếu.
   */
  checklist_completed: Generated<boolean>;
  completed_at: Timestamp | null;
  id: Generated<string>;
  machine_id: string;
  /**
   * Nullable vì phiếu được mở trước khi chọn chai thay thế (FR-INV-29). Domain service phải bảo đảm NOT NULL trước khi status chuyển COMPLETED — xem §13.
   */
  new_bottle_id: string | null;
  notes: string | null;
  old_bottle_id: string | null;
  performed_by: string;
  slot_id: string;
  started_at: Generated<Timestamp>;
  status: Generated<RefillStatus>;
}

export interface RefreshSessions {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  ip_address: string | null;
  last_used_at: Timestamp | null;
  revoked_at: Timestamp | null;
  /**
   * Chỉ lưu băm của refresh token, không lưu token gốc (NFR-SEC-05). TTL: REFRESH_TOKEN_TTL_DAYS.
   */
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface RolePermissions {
  created_at: Generated<Timestamp>;
  permission_id: string;
  role_id: string;
}

export interface Roles {
  /**
   * NULL với vai trò mức nền tảng/hệ thống.
   */
  brand_id: string | null;
  code: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_system: Generated<boolean>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface SensorReadings {
  id: Generated<string>;
  machine_id: string;
  measured_at: Timestamp;
  numeric_value: Numeric | null;
  payload: Json | null;
  reading_type: string;
  received_at: Generated<Timestamp>;
  slot_id: string | null;
  unit: string | null;
}

export interface SlotRentalRequests {
  brand_id: string;
  created_at: Generated<Timestamp>;
  desired_ends_at: Timestamp;
  desired_starts_at: Timestamp;
  id: Generated<string>;
  rejection_reason: string | null;
  requested_by: string;
  /**
   * Đặt khi yêu cầu được duyệt và hợp đồng DRAFT được tạo tự động (FR-SLT-23).
   */
  resulting_rental_id: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  slot_id: string;
  status: Generated<SlotRentalRequestStatus>;
  updated_at: Generated<Timestamp>;
}

export interface SlotRentals {
  brand_id: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: Generated<string>;
  ends_at: Timestamp;
  fixed_fee: Generated<Numeric>;
  /**
   * Nullable ở tầng CSDL CHỈ để cho phép cửa sổ DRAFT giữa FR-SLT-23 (tạo hợp đồng tự động) và FR-SLT-27 (Brand Admin gán sản phẩm). Domain service phải chặn tạo đơn khi cột này NULL (FR-SLT-29). Xem §13.
   */
  fragrance_product_id: string | null;
  /**
   * Ngày kết thúc ân hạn do Platform Super Admin ấn định (FR-EXP-07).
   */
  grace_ends_at: Timestamp | null;
  id: Generated<string>;
  /**
   * Hợp đồng liền trước khi đây là hợp đồng gia hạn (FR-SLT-12).
   */
  previous_rental_id: string | null;
  price_per_spray: Numeric;
  product_assigned_at: Timestamp | null;
  request_id: string | null;
  revenue_share_percent: Generated<Numeric>;
  slot_id: string;
  starts_at: Timestamp;
  status: Generated<SlotRentalStatus>;
  terminated_reason: string | null;
  updated_at: Generated<Timestamp>;
}

export interface UserRoles {
  assigned_at: Generated<Timestamp>;
  assigned_by: string | null;
  id: Generated<string>;
  role_id: string;
  /**
   * Id địa điểm hoặc máy khi scope_type yêu cầu (FR-AUTH-12). NULL với scope PLATFORM/BRAND.
   */
  scope_id: string | null;
  scope_type: Generated<string>;
  user_id: string;
}

export interface Users {
  /**
   * NULL với tài khoản mức nền tảng (Platform Super Admin, Operations Staff, Inventory Staff). Brand Admin bắt buộc có giá trị (FR-AUTH-05).
   */
  brand_id: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  full_name: string;
  id: Generated<string>;
  last_login_at: Timestamp | null;
  password_hash: string;
  /**
   * Tăng lên khi vai trò/quyền đổi, để vô hiệu hóa access token đang lưu hành (FR-AUTH-10).
   */
  permission_version: Generated<number>;
  status: Generated<UserStatus>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  alerts: Alerts;
  audit_logs: AuditLogs;
  bottles: Bottles;
  brand_shipment_declarations: BrandShipmentDeclarations;
  brands: Brands;
  device_credentials: DeviceCredentials;
  device_events: DeviceEvents;
  dispense_commands: DispenseCommands;
  dispense_results: DispenseResults;
  fragrance_products: FragranceProducts;
  inventory_adjustments: InventoryAdjustments;
  inventory_batches: InventoryBatches;
  kiosk_interaction_events: KioskInteractionEvents;
  locations: Locations;
  machine_slots: MachineSlots;
  machine_status_histories: MachineStatusHistories;
  machines: Machines;
  maintenance_activities: MaintenanceActivities;
  maintenance_tickets: MaintenanceTickets;
  notifications: Notifications;
  order_status_histories: OrderStatusHistories;
  orders: Orders;
  payment_events: PaymentEvents;
  payments: Payments;
  permissions: Permissions;
  refill_requests: RefillRequests;
  refill_sessions: RefillSessions;
  refresh_sessions: RefreshSessions;
  role_permissions: RolePermissions;
  roles: Roles;
  sensor_readings: SensorReadings;
  slot_rental_requests: SlotRentalRequests;
  slot_rentals: SlotRentals;
  user_roles: UserRoles;
  users: Users;
}
