// SINH TỰ ĐỘNG từ spec/constraints.md bằng `npm run spec:generate`. KHÔNG SỬA TAY.
// Muốn đổi: sửa spec/constraints.md rồi chạy lại lệnh trên.

export const SPEC_CONSTRAINTS = {
  HEARTBEAT_INTERVAL_SEC: 30,
  MACHINE_UNSTABLE_MISSED: 2,
  MACHINE_OFFLINE_SEC: 90,
  DEVICE_EVENT_BUFFER_MIN: 500,
  ORDER_PAYMENT_TTL_SEC: 300,
  ORDER_STATUS_POLL_MAX_SEC: 3,
  DISPENSE_CMD_TTL_SEC: 60,
  DISPENSE_RESULT_TIMEOUT_SEC: 60,
  WEBHOOK_TO_ACTUATION_MAX_SEC: 5,
  ACTUATOR_MAX_MS: 800,
  ACTUATOR_RUN_MS: 500,
  ACCESS_TOKEN_TTL_MIN: 60,
  REFRESH_TOKEN_TTL_DAYS: 7,
  LOGIN_LOCKOUT_ATTEMPTS: 5,
  LOGIN_LOCKOUT_MIN: 15,
  SESSION_REVOKE_MAX_SEC: 60,
  REAUTH_TOKEN_TTL_SEC: 300,
  RENTAL_EXPIRING_DAYS: 7,
  RENTAL_NOTICE_DAYS: [7, 3],
  GRACE_FEE_RATE_DEFAULT: 0.05,
  DOOR_OPEN_ALERT_MIN: 5,
  CONSECUTIVE_FAIL_ALERT: 3,
  LEAK_DETECT_THRESHOLD_PCT: 20,
  BATCH_EXPIRY_WARN_DAYS: 30,
  INVENTORY_TOLERANCE_PCT: 10,
  KIOSK_IDLE_TIMEOUT_SEC: 60,
  KIOSK_MIN_FONT_PX: 18,
  ORDER_RATE_LIMIT_PER_MIN: 10,
  KIOSK_SELECT_RESPONSE_MAX_MS: 500,
} as const;

export type ConstraintName = keyof typeof SPEC_CONSTRAINTS;
